name: fullstack_todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  data_source:
    path: ../data_source
  exceptions:
    path: ../exceptions
  failures:
    path: ../failures
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  fpdart: ^1.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  models:
    path: ../models
  repository:
    path: ../repository
  retrofit: ^4.4.2
  typedefs:
    path: ../typedefs

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.1.9

flutter:

  uses-material-design: true
