name: full_stack_todo
description: A full stack todo app with a Flutter frontend and a Dart backend.

packages:
  - backend/

scripts:
  backend:dev:
    run: melos exec -c 1 --fail-fast -- "dart_frog dev"
    description: Starts the dev server for the backend
    select-package:
      flutter: false