name: full_stack_todo
publish_to: none

environment:
  sdk: ^3.7.2

workspace:
  - backend
  - models
  - typedefs
  - failures
  - data_source
  - repository
  - exceptions

dev_dependencies:
  melos: ^6.3.2
