name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
