name: failures
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
   freezed_annotation: ^3.0.0
   json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
   mocktail: ^1.0.4
   test: ^1.25.15
   lints: ^5.0.0
   freezed: ^3.0.6
   json_serializable: ^6.9.5
   build_runner: ^2.4.15
